### ISSUE TITLE
Problem: Problem tracker is difficult to use

### ISSUE THREAD

**Issue by shaibearary** [Stackerstan/interfarce#14]
It's difficult to interact with the problem tracker. I have to scroll through a lot of text before getting to anything actionable.

Simplest solution is probably to collapse the problems and only show their heading and maybe a couple of lines.

To make it easier to quickly reason about the list of problems, perhaps colour code them by their status: open and claimable; claimed by me; can't be claimed because someone else has claimed it; can't be claimed because there are children; can't be claimed becuase it's closed;

---------------------------------------------------------------------------------------------------------
I make a simplest solution of collapse problems and click to see details
Please check and see if it can be merged
@stanstacks

**Comment by stanstacks** [comment]
Thank you @pqingshuang! It's merged and should be live in a few minutes when the cache refreshes. I've also invited you into the organisation, you should get an email.

**Comment by shaibearary** [comment]
yeah, I got it. Thankssssss. glad to help  🥰

**Comment by shaibearary** [comment]
pubkey: cc8d072efdcc676fcbac14f6cd6825edc3576e55eb786a2a975ee034a6a026cb
Expense: 488888 Sats
