### ISSUE TITLE
Problem: can't use window.nostr to sign

### ISSUE THREAD

**Issue by stanstacks** [Stackerstan/interfarce#2]
problem: you currently need to use the autogenerated private key and can't safely sign with an existing nostr private key because getalby and nos2x don't work

**Comment by bitkarrot** [comment]
use getAlby. Assign it to me

**Comment by bitkarrot** [comment]
Account seed words need to be converted to hex and then bech32 nsec format for use with getalby and nos2x.

**Comment by bitkarrot** [comment]
I have forked https://github.com/nbd-wtf/nostr-tools to stackerstan as a reference toolkit. It should help with key conversion and signing moving forward instead of having to roll our own tools. 

the toolkit can also be included in the script tag which will work with the current setup

**Comment by shaibearary** [comment]
@stanstacks

**Comment by stanstacks** [comment]
Looks like this was solved by @gazhayes?
