### ISSUE TITLE
Problem: cannot open "my account" if alby installed but not used

### ISSUE THREAD

**Issue by shaibearary** [Stackerstan/interfarce#26]
![image](https://user-images.githubusercontent.com/26760878/214756569-e1483d87-6ef3-40a6-8076-6bc25d282561.png)

**Comment by stanstacks** [comment]
I can't reproduce this. Do you mean it doesn't open at all?

**Comment by shaibearary** [comment]
I'm sorry maybe it's my network problem. I did t see this problem now.

**Comment by shaibearary** [comment]
@stanstacks 
ok i reproduce this haha. 
my description on title was wrong
so first, have alby installed. 
Second, open stackertan.org, the login window will pop up. 
Third, close the pop up window. 
The web is supposed to link to the accout stored at brower right ? Then click 'My account', the page wont have any reaction.

**Comment by shaibearary** [comment]
![image](https://user-images.githubusercontent.com/26760878/217483546-55c06477-f611-4c78-9bb8-a24cf30fbdcb.png)

**Comment by stanstacks** [comment]
> The web is supposed to link to the accout stored at brower right ? Then click 'My account', the page wont have any reaction.

If you have alby or nos2x installed it should not give you the option of using a private key or seed words, you should use the extension instead.
