### ISSUE TITLE
problem: can't submit expenses

### ISSUE THREAD

**Issue by stanstacks** [Stackerstan/interfarce#4]
problem: can't submit expenses

solution: implement Kind 640204 on the frontend

https://github.com/Stackerstan/mindmachine/blob/ab91e9d138214e4fe0e8d73b7cfa7b5dfa969bf1/consensus/shares/types.go#L50

**Comment by shaibearary** [comment]
Hi @stanstacks 
I run into the problem again that cannot test on mainnet while trying to solve this problem. Is there anyway to reduce the potential danger currently

**Comment by stanstacks** [comment]
There isn't really, but just test it with your own real expense in case it works. It shouldn't actually break anything if you mess it up because the other mindmachines will just reject it.

I saw that you claimed and solved 3c19032d8d511911a4b4f5681e4b04a1b67976c825a7b6f789654200b2a85090 so you could use that for testing (expenses require you to state the ID of the problem)

For the ID of the patch, take the patch you submitted: https://github.com/Stackerstan/interfarce/commit/d7668839bf1ca0685ad53c5f5c99c02c7b7808ba.diff

And hash that file with sha256.

**Comment by shaibearary** [comment]
> 
@stanstacks 
Thanks for answering. Do i need to hash the input expense amount? What kind of info should be harshed? I saw that in Problem, Title and description are being harshed.

**Comment by stanstacks** [comment]
Have a look at Kind640204 in /consensus/shares/types.go

The problem should just be an existing problem hash (the ID of a problem).
Solution is the sha256 hash of the patch itself (the diff I posted above)
Amount is just an int64 (satoshis), so in javascript that's just a "number".

### Sequence Number
Sequence needs to be the current sequence on the account's shares object + 1
This is is the only thing right now which is not implemented on the frontend. The mindmachine is not currently sending the shares object for accounts to the frontend. 

If you have a look at eventers.allIdentities() you can see how the current state of the Identities Mind is transmitted to the interfarce with Kind640499 events. On the interfarce you can search for 640499 to see how this is handled.

You could copy this logic and do the same thing for Shares as I did with Identities, and part of that would be any existing expenses, the sequence number, etc.

### Creating the event
You need to create and sign a Kind 640204 event on the frontend to submit an expense. It's worth looking at how other events are created, such as setting your username and bio, logging a problem, etc. That should give you a good idea of how to do it. 

In Problems, the Title and Description aren't being hashed exactly, the content of them are being turned into Kind 1 events, and the ID of the Kind1 event is a hash of all the data in the event. Then the Mindmachine combines all this into a single Problem in the issue tracker. But for expenses, you don't need to do that, it's a more simple.
