### ISSUE TITLE
Problem: maintainers can't easily see when someone edits a doki

### ISSUE THREAD

**Issue by stanstacks** [Stackerstan/interfarce#6]
Problem: maintainers can't easily see when someone edits a doki

I just noticed that someone submitted patches to two of the doki's (thanks, whoever you are).

I only noticed because I happened to be watching the CLI and saw one of the events come in.

Currently the only way to see if there are doki patches waiting to be merged is by opening every doki and checking. This is very slow and annoying. 

Simplest solution is probably some kind of "maintainer feed" where you can see this.

**Comment by shaibearary** [comment]
Hi,
I tried to solve this problem by highlight the doki if it has unmerged patch as the screenshot below, do you feel it is acceptable?
![image](https://user-images.githubusercontent.com/26760878/209564284-9c35594a-6ada-43e8-b34d-c2ec9b0b5bd6.png)
Also, I edited the doki showing as hightlight on the screenshot above as a test of my code, would you mind helping reject it 🤣haha

**Comment by stanstacks** [comment]
Nice work @pqingshuang!

FYI when you solve an issue like this, you should post a comment including your stackerstan pubkey and also the total value of the time you spent, denominated in satoshi. That way you can claim an Expense to get Shares (once I implement that on the frontend).

So, take your usual hourly rate (or whatever you are happy with), calculate that in satoshi at the current Bitcoin price, and multiply by how long you spent on solving the issue.

E.g. US$50 an hour = 0.00297619 BTC = 297,619 Sats
2 hours *  297,619 = 595238 Sats

So you would append this to an issue that you have solved:

pubkey: cc8d072efdcc676fcbac14f6cd6825edc3576e55eb786a2a975ee034a6a026cb
Expense: 595238 Sats

**Comment by shaibearary** [comment]
OK. 

pubkey: cc8d072efdcc676fcbac14f6cd6825edc3576e55eb786a2a975ee034a6a026cb
Expense: 588888 Sats
